// src/app/layout.tsx
import "@uploadthing/react/styles.css";   // REQUIRED

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}

        {/* IMPORTANT: UploadThing client script MUST be inside <body> LAST */}
        <script 
          src="https://uploadthing.com/client/script"
          data-ut-element="auto"
        ></script>
      </body>
    </html>
  );
}
